baseurl = "http://michal.klimuk.me/"
languageCode = "en-us"
title = "Michal Klimuk"
theme = "hugo-nuo"
pygmentsuseclasses = true
PygmentsCodeFences = true

[params]
  github = "mklimuk"
  twitter = "m1s13q"
  linkedin = "mklimuk"
  Summary = false
  Content = false
  subtitle = "~Â code, share, smile ~"
  avatar = "/images/avatar.jpg"
